### ISSUE TITLE
kafka cluster-- producer get "local_inconsistent" error when I stop one broker, when I re-run, i always get timeout error in  producer.InitTransactions

### ISSUE THREAD

**Issue by wushuaizaiza** [confluentinc/confluent-kafka-dotnet#1768]
Description
===========
1.Confluent.kafka version is 1.7.0.
2. Create kafka cluster by using one zookeeper, 3 brokers, 2 partions.
3. during produce kafka message, when i stop borker 1, get "Local_inconsistent" error and don't reuse other broker to deal with message

How to reproduce
===========
1. Create Kafka cluster by using 3 brokers. 3 broker detail is:
broker.id=1
host.name=10.62.156.217
port=9092
broker.id=2
host.name=10.62.156.220
port=9093

broker.id=3
host.name=10.62.156.231
port=9094

2. created topic MYTEST1 with Replication factor 3 and partition 2
As you can see broker 3 is leader of Partition 0
and broker 1 is leader of partition 1
[root@ustr-mvm-2796 kafka_2.13-2.7.0]# bin/kafka-topics.sh --describe --zookeeper localhost:2181 --topic MYTEST1
Topic: MYTEST1    PartitionCount: 2    ReplicationFactor: 3    Configs: 
    Topic: MYTEST1    Partition: 0    Leader: 3    Replicas: 3,2,1    Isr: 3,2,1
    Topic: MYTEST1    Partition: 1    Leader: 1    Replicas: 1,3,2    Isr: 1,3,2
[root@ustr-mvm-2796 kafka_2.13-2.7.0]#

3.bring down broker 1, and then producer message,
As you can see after bring down the broker 1, leader of partion is 3.
[root@ustr-mvm-2796 kafka_2.13-2.7.0]# bin/kafka-topics.sh --describe --zookeeper localhost:2181 --topic MYTEST1
Topic: MYTEST1    PartitionCount: 2    ReplicationFactor: 3    Configs: 
    Topic: MYTEST1    Partition: 0    Leader: 3    Replicas: 3,2,1    Isr: 3,2
    Topic: MYTEST1    Partition: 1    Leader: 3    Replicas: 1,3,2    Isr: 3,2

4. get "local_inconsistent" error
5. re-run my producer , get time out error when init producer.

Checklist
=========

Please provide the following information:
 - [ ] A complete (i.e. we can run it), minimal program demonstrating the problem. No need to supply a project file.
 - [ ] Confluent.Kafka nuget version.
 - [ ] Apache Kafka version.
 - [ ] Client configuration.
 - [ ] Operating system.
 - [ ] Provide logs (with "debug" : "..." as necessary in configuration).
 - [ ] Provide broker log excerpts.
 - [ ] Critical issue.

**Comment by edenhill** [comment]
Can you try to reproduce this on latest client version 1.8.2? We've fixed some transactional issues after 1.7.0

**Comment by wushuaizaiza** [comment]
hi @edenhill,

i use the latest client version 1.8.2, still encounter timeout error -- "Failed to initialize Producer ID: Local: Timed out"

**Comment by wushuaizaiza** [comment]
I create new kafka cluster to test, and get this error: "Failed to initialize Producer ID: Broker: Producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing".

I also test that: start 3 kafka instance as a kafka cluster by using docker in one machine, and then stop one leader kafka broker, then don't get any error for "initTranscations", it works fine.

**Comment by mhowlett** [comment]
> "Failed to initialize Producer ID: Broker: Producer attempted to update a transaction while another concurrent operation on the same transaction was ongoing"

The current version of librdkafka has an error in the KIP-360 logic whereby InitProducerId being called before the transaction is aborted. We have a fix (not merged yet), and have been doing a lot of related testing.

I'm closing this preemptively (currently going through triaging .net issues). Please open again if this problem persists past the next version of librdkafka (unsure if this'll be a 1.9.x release or 1.1.0)
