### ISSUE TITLE
Automatic load for librdkafka libraries not working in NetFramework projects with 2.6.0

### ISSUE THREAD

**Issue by dmalanij** [confluentinc/confluent-kafka-dotnet#2328]
Description
===========
When using the libraries in Net 4.8 project (in particular a _WebAPI_), as of `2.6.0` the initialization of the `Confluent.Kafka.Impl.Librdkafka` initialization fails with a `DllNotFoundException` and the message:
> Failed to load the librdkafka native library.

How to reproduce
================
In a _NetFramework_ project, reference to the latest version of the `Confluent.Kafka` package; as soon as the runtime reaches the Kafka initialization (ie: using the `ProducerBuilder<,>`) the exception is thrown even if the redist assemblies are in place (in particular in the `bin\librdkafka` as the `librdkafka.redist` package targets take care of). 

Root cause Analysis
================
I believe that the problem is hapenning because `2.6.0` has not included the target for `net462`; therefore the initialization goes through [the _netstandard_ variation](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/LibRdKafka.cs#L585)  without the automatic path resolution that is present for the [cases of _net462_](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/LibRdKafka.cs#L561).

## Workaround
This can be avoided by simply including a call to `Library.Load(path)` where `path` contains the location for the `librdkafka.dll` (which in case can be ~ripped of~ inspired in the logic used by the [implementation](https://github.com/confluentinc/confluent-kafka-dotnet/blob/master/src/Confluent.Kafka/Impl/LibRdKafka.cs#L585) of the `LoadNetFrameworkDelegates`.

**Comment by UBSaxo** [comment]
We face same blocking issue. I cloned `Confluent.Kafka` and could easily reproduce it simply by changing the target framework of `Confluent.Kafka.UnitTests` test project to `net48` and then loads of tests fail with the `DllNotFoundException`.

**Comment by anchitj** [comment]
Can you try with 2.6.1? We've added back `net462`

**Comment by dmalanij** [comment]
> Can you try with 2.6.1? We've added back `net462`

I'll give it a try as soon as I can, right now we're in the final stage of our release cycle so the dependencies are fixed.
Cheers

**Comment by UBSaxo** [comment]
I have validated this by running your own unit tests against net48 and that works. With 2.6.0 that failed.

I would still love to see your automated tests extended to also cover NET Framework to avoid this mistake from repeating itself in future.

**Comment by samuelburnett** [comment]
I am still encountering this issue. I have a NET Framework 4.8 project that references 2.6.1 and receive the following error at runtime:
`Error while loading librdkafka.dll or its dependencies from C:\PATH_TO_PROJECT\bin\Debug\librdkafka.dll.`

No issue in my NET 6 project referencing 2.6.1.

**Comment by dmalanij** [comment]
> Can you try with 2.6.1? We've added back `net462`

Finally we were able to do the update and, same as @UBSaxo, the code is working fine now with `2.6.1`.
