### ISSUE TITLE
How to set message.timeout.ms for Producer

### ISSUE THREAD

**Issue by McMlok** [confluentinc/confluent-kafka-dotnet#322]
I want to get error faster than after 5min if brokers are down. I found that options message.timeout.ms is for it. But when I set this options when I creating Producer instance and call ProduceAsync I get result with error after 5min.

I create producer like this
var config = new KeyValuePair<string, string>[]{ 
  new KeyValuePair<string, string>("message.timeout.ms", "1000"),
  new KeyValuePair<string, string>("bootstrap.servers", "server:9092"),
}
_producer = new Producer(config, false, false);

Thanks

Checklist
=========
Please provide the following information:

 - [ ] Confluent.Kafka nuget version: 0.11.0

**Comment by mhowlett** [comment]
try setting `message.timeout.ms` under `default.topic.config`, and also note that `message.send.max.retries` will also affect how long it takes before you get an error. eg:

```
            var pConfg = new Dictionary<string, object>()
            {
                { "bootstrap.servers", "localhost:9092" },
                { "default.topic.config", new Dictionary<string, object>()
                    {
                        { "message.timeout.ms", 5000 }
                    }
                },
                { "message.send.max.retries", 0 }
            };
```

In 0.11.0, my understanding was that librdkafka should now recognize topic level configuration properties at the top level (as you are doing), however I just tested this and it didn't appear to work here @edenhill .

**Comment by edenhill** [comment]
@mhowlett It does, and it creates an implicit default topic configuration object internally for those properties, but this config object is then replaced when the .NET bindings call set_default_topic_config().

**Comment by mhowlett** [comment]
ahh ok. I think the way to solve this is promote any default.topic.config settings to the top level in the producer constructor and then never call set_default_topic_config. a warning would be good - though we don't really have a good mechanism for doing it. We could maybe warn by writing to stderr or firing and event on OnError, but neither are ideal.

**Comment by edenhill** [comment]
I meant a documentation warning.

**Comment by McMlok** [comment]
@mhowlett thanks your config works as I expected.

**Comment by mhowlett** [comment]
addressed in #410

**Comment by SauravChe1905** [comment]
@edenhill I am currently using Confluent V0.11.4-RC2. Iam able to set the timeout directly at the top level. But if my Broker is unavailable I still get the error message as "timeout". Here is th code:
	var config = new Dictionary<string, object>
      {
        { "bootstrap.servers", brokerTestNoSecurity },
	{"message.timeout.ms", 1000},
	    };
 using (var producer = new Producer<Null, string>(config, null, new StringSerializer(Encoding.UTF8)))
      {
        Console.WriteLine($"{producer.Name} producing on {topicName}. q to exit.");


        string text;
        while ((text = Console.ReadLine()) != "q")
        {
					var deliveryReport = producer.ProduceAsync(topicName, null, text);

					deliveryReport.ContinueWith(task =>
					{
						Console.WriteLine($"Partition: {task.Result.Partition}, Offset: 
                                                {task.Result.Offset}");
					});
					var x = deliveryReport.Result;
        }
        producer.Flush(TimeSpan.FromSeconds(10));

**Comment by sholehabibibetsson** [comment]
there is no support for Dictionary<string, object>() in 1.0.0 ... How could we be able to use "message.timeout.ms"?

**Comment by adduca01** [comment]
> there is no support for Dictionary<string, object>() in 1.5.0 ... How could we be able to use "message.timeout.ms"?

Would suggest using ProducerConfig in Confluent.Kafka. It has a settable property "MessageTimeoutMs".
