### ISSUE TITLE
SafeKafkaHandle.ReleaseHandle crash

### ISSUE THREAD

**Issue by jbouzaglou** [confluentinc/confluent-kafka-dotnet#463]
Description
===========
When launching some kafka code under nunit, there is an unhandled exception in SafeKafkaHandle.ReleaseHandle. This crashes all our integration tests.
I manage to reproduce it with a very simple project, but only with debug producer logging in librdkafka enabled, if you remove it i cannot reproduce.
This might be a hard to find race condition in the free routine?

How to reproduce
================
Test project is attached, to make it crash you need to use the nunit 3.4.1 runner, the command line used in nunit is ".\nunit3-console.exe ..\..\..\KafkaCrashTest\bin\Release\KafkaCode.dll". It should crash within a minute.
[KafkaCrashTest.zip](https://github.com/confluentinc/confluent-kafka-dotnet/files/1816431/KafkaCrashTest.zip)

Checklist
=========
Please provide the following information:

 - [ x] Confluent.Kafka nuget version: 0.11.3
 - [ x] Apache Kafka version: kafka_2.11-0.11.0.1
 - [ x] Client configuration: included in project
 - [ x] Operating system: Windows 10
 - [ x] Provide logs (with "debug" : "..." as necessary in configuration) : you have the full code
 - [ x] Provide broker log excerpts :no logs as it doesnt require a broker to be up
 - [] Critical issue

**Comment by mhowlett** [comment]
I believe this has been fixed in master (try this build):
https://ci.appveyor.com/project/ConfluentClientEngineering/confluent-kafka-dotnet/build/1.0.315

(not available on nuget.org yet)

**Comment by jbouzaglou** [comment]
Hello,
I pulled the tip of master and compiled in Release, then used in my test project, still the same crash. I doubt this commit has any impact as well, the call stack is like this when crashing : 
![debug vs](https://user-images.githubusercontent.com/2351915/37513418-f7683646-28fc-11e8-8b93-d6751d6c429d.PNG)

Please could you run it according to the instructions and see if it reproduces on your end? You have the whole project (1 code file really) in the zip, and just run the nunit command form the nunit tool packages folder

**Comment by mhowlett** [comment]
@jbouzaglou thanks for going to the trouble of making a simple reproducible test, looks good. It seems like this is probably bug, I'll investigate. Unfortunately I can't get to it immediately, but I do view it as important to get to the bottom of.

**Comment by mhowlett** [comment]
I believe this is the same issue as, or will be remedied by work done in #577. Tracking this over there.
